title: Lovedeep Sharma # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 DevOps Engineer
  <br><br>
  <a href="Email: sharmalovedeep93@gmail.com"></a>
  <br>
  <a href="LinkedIn Profile: https://www.linkedin.com/in/lovedeep-sharma-715ba5179/"></a>
  <br>
  <a href="Gihub: https://github.com/lovedeepsh"></a> 
  <br>
  <a href="Stack Overflow: https://bit.ly/35OrbGz"></a>
theme: jekyll-theme-minimal
